<?php require('templates/header.phtml') ?>

<div class="About-Us">
    <div class="container">
        <div class="row">
            <h6> - Our Mission -</h6>
            <p> Lorem ipsum dolor sit amet, consectetur adipiscing elit. Nullam ac rutrum lacus. Duis finibus velit ut
                augue interdum tempus. Donec dignissim bibendum turpis ut cursus.</p>
        </div>

        <div class="row centre_text">
            <h6> What Is ECO_? </h6>

            <p> The ECO_ concept represents the fundamental principles of Enviroment, Community and Organizations, it is
                a multisided platform that connects together two or more independent groups controlled in the interest
                of Oppurtunity value and impact to form ECO ambassadors , ECO leaders and ECO organizations. We work to
                share, create and sustain. Our platform allows groups to share knowledge and ideas with people and
                organizations around the globe with the intention to create, economic, social and enviromental
                opportunities, through sustainable impact.

                <br><br><span class="Bold">Change the world through Collaboration.</span></p>
        </div>
    </div>
</div>


<div class="Team">
    <div class="container">
        <div class="row">
            <h6> Our Team </h6>

            <p> Lorem ipsum dolor sit amet, consectetur adipiscing elit. Nullam ac rutrum lacus. Duis finibus velit ut
                augue interdum tempus. Donec dignissim bibendum turpis ut cursus. Pellentesque placerat euismod lorem,
                Lorem ipsum dolor sit amet, consectetur adipiscing elit. Nullam ac rutrum lacus. Duis finibus velit ut
                augue interdum tempus. Donec dignissim bibendum turpis ut cursus. Pellentesque placerat euismod
                lorem,</p>
        </div>

        <div class="row mgt50px">

            <div class="row">

                <div class="col-sm-3">
                    <div class="Member">
                        <div class="imgBox">
                            <img src="Images/sam.jpg" alt="personPic">
                        </div>
                        <div class="details">
                            <h3>Sam Obeghe<br><span>Founder</span></h3>
                            <ul>
                                <li><a href="#"><i class="fa fa-facebook" aria-hidden="true"></i></a></li>
                                <li><a href="#"><i class="fa fa-twitter" aria-hidden="true"></i></a></li>
                                <li><a href="#"><i class="fa fa-instagram" aria-hidden="true"></i></a></li>
                                <li><a href="#"><i class="fa fa-google-plus" aria-hidden="true"></i></a></li>
                                <li><a href="#"><i class="fa fa-linkedin" aria-hidden="true"></i></a></li>
                            </ul>
                        </div>
                    </div>
                </div>
            </div>
        </div>


    </div>
</div>

<?php require('templates/footer.phtml') ?>

