<?php require('templates/header.phtml') ?>


    <div id="carouselExampleIndicators" class="carousel slide" data-ride="carousel">
        <ol class="carousel-indicators">
            <li data-target="#carouselExampleIndicators" data-slide-to="0" class="active"></li>
            <li data-target="#carouselExampleIndicators" data-slide-to="1"></li>
            <li data-target="#carouselExampleIndicators" data-slide-to="2"></li>
            <li data-target="#carouselExampleIndicators" data-slide-to="3"></li>
            <li data-target="#carouselExampleIndicators" data-slide-to="4"></li>
        </ol>
        <div class="carousel-inner" role="listbox">

            <div class="carousel-item active" style="background-image: url('../Images/Filler.jpg')">
                <div class="carousel-caption">


                    <h3 class="font-weight-normal display-3"><span class="HeadGreen">E</span><span
                                class="HeadYellow">C</span><span class="HeadBlue">O</span> <span class="HeadGreen">AFRICA</span>
                    </h3>
                    <p class="BodyText">Enviroment, Community, Organisation</p>
                    <p class="LowerBodyText">Connecting students all around the world for a better AFRICA</p>

                    <div class="Buttons">
                        <div class="container">
                            <div class="row">
                                <div class="col-sm-4 right-button">
                                    <a href="">
                                        <div class="Textbox-outside">
                                            <div class="row">
                                                <div class="col-sm-12">
                                                    <div class="Text-inside">
                                                        <h4>E For Environment </h4>
                                                        <p>Find Out More > </p>
                                                    </div>
                                                </div>
                                            </div>
                                        </div>
                                    </a></div>


                                <div class="col-sm-4 center-button">
                                    <a href="">
                                        <div class="Textbox-outside">
                                            <div class="row">
                                                <div class="col-sm-12">
                                                    <div class="Text-inside">
                                                        <h4>C For Community </h4>
                                                        <p>Find Out More > </p>
                                                    </div>
                                                </div>
                                            </div>
                                        </div>
                                    </a></div>


                                <div class="col-sm-4 left-button">
                                    <a href="">
                                        <div class="Textbox-outside">
                                            <div class="row">
                                                <div class="col-sm-12">
                                                    <div class="Text-inside">
                                                        <h4>O For Organisation</h4>
                                                        <p>Find Out More > </p>
                                                    </div>
                                                </div>
                                            </div>
                                        </div>
                                    </a></div>


                            </div>
                        </div>
                    </div>
                </div>


            </div>
            <!-- Slide Two - Set the background image for this slide in the line below -->
            <div class="carousel-item" style="background-image: url('../Images/Filler.jpg')">
                <div class="carousel-caption">


                    <h3 class="font-weight-normal display-3">Earn IFA</h3>
                    <p class="BodyText">Get Rewards, Build a reputation while innovating for Africa</p>
                    <p class="LowerBodyText">Connecting students all around the world for a better AFRICA</p>

                    <div class="Buttons">
                        <div class="container">
                            <div class="row">
                                <div class="col-sm-4 right-button">
                                    <a href="">
                                        <div class="Textbox-outside">
                                            <div class="row">
                                                <div class="col-sm-12">
                                                    <div class="Text-inside">
                                                        <h4>E For Environment </h4>
                                                        <p>Find Out More > </p>
                                                    </div>
                                                </div>
                                            </div>
                                        </div>
                                    </a></div>


                                <div class="col-sm-4 center-button">
                                    <a href="">
                                        <div class="Textbox-outside">
                                            <div class="row">
                                                <div class="col-sm-12">
                                                    <div class="Text-inside">
                                                        <h4>C For Community </h4>
                                                        <p>Find Out More > </p>
                                                    </div>
                                                </div>
                                            </div>
                                        </div>
                                    </a></div>


                                <div class="col-sm-4 left-button">
                                    <a href="">
                                        <div class="Textbox-outside">
                                            <div class="row">
                                                <div class="col-sm-12">
                                                    <div class="Text-inside">
                                                        <h4>O For Organisation</h4>
                                                        <p>Find Out More > </p>
                                                    </div>
                                                </div>
                                            </div>
                                        </div>
                                    </a></div>


                            </div>
                        </div>
                    </div>

                </div>
            </div>
            <!-- Slide Three - Set the background image for this slide in the line below -->
            <div class="carousel-item" style="background-image: url('../Images/Filler.jpg')">
                <div class="carousel-caption">
                    <h3 class="font-weight-normal display-3">Innovation Meter</h3>
                    <p class="BodyText">Crystal clear insight of Africa Devlopment</p>
                    <p class="LowerBodyText">Connecting students all around the world for a better AFRICA</p>

                    <div class="Buttons">
                        <div class="container">
                            <div class="row">
                                <div class="col-sm-4 right-button">
                                    <a href="">
                                        <div class="Textbox-outside">
                                            <div class="row">
                                                <div class="col-sm-12">
                                                    <div class="Text-inside">
                                                        <h4>E For Environment </h4>
                                                        <p>Find Out More > </p>
                                                    </div>
                                                </div>
                                            </div>
                                        </div>
                                    </a></div>


                                <div class="col-sm-4 center-button">
                                    <a href="">
                                        <div class="Textbox-outside">
                                            <div class="row">
                                                <div class="col-sm-12">
                                                    <div class="Text-inside">
                                                        <h4>C For Community </h4>
                                                        <p>Find Out More > </p>
                                                    </div>
                                                </div>
                                            </div>
                                        </div>
                                    </a></div>


                                <div class="col-sm-4 left-button">
                                    <a href="">
                                        <div class="Textbox-outside">
                                            <div class="row">
                                                <div class="col-sm-12">
                                                    <div class="Text-inside">
                                                        <h4>O For Organisation</h4>
                                                        <p>Find Out More > </p>
                                                    </div>
                                                </div>
                                            </div>
                                        </div>
                                    </a></div>


                            </div>
                        </div>
                    </div>


                </div>
            </div>


            <div class="carousel-item" style="background-image: url('../Images/Filler.jpg')">
                <div class="carousel-caption">


                    <h3 class="font-weight-normal display-3">Opportunities</h3>
                    <p class="BodyText">Opportunities, Jobs, Apprenticeships, Volunteering in AFRICA</p>
                    <p class="LowerBodyText">Connecting students all around the world for a better AFRICA</p>

                    <div class="Buttons">
                        <div class="container">
                            <div class="row">
                                <div class="col-sm-4 right-button">
                                    <a href="">
                                        <div class="Textbox-outside">
                                            <div class="row">
                                                <div class="col-sm-12">
                                                    <div class="Text-inside">
                                                        <h4>E For Environment </h4>
                                                        <p>Find Out More > </p>
                                                    </div>
                                                </div>
                                            </div>
                                        </div>
                                    </a></div>


                                <div class="col-sm-4 center-button">
                                    <a href="">
                                        <div class="Textbox-outside">
                                            <div class="row">
                                                <div class="col-sm-12">
                                                    <div class="Text-inside">
                                                        <h4>C For Community </h4>
                                                        <p>Find Out More > </p>
                                                    </div>
                                                </div>
                                            </div>
                                        </div>
                                    </a></div>


                                <div class="col-sm-4 left-button">
                                    <a href="">
                                        <div class="Textbox-outside">
                                            <div class="row">
                                                <div class="col-sm-12">
                                                    <div class="Text-inside">
                                                        <h4>O For Organisation</h4>
                                                        <p>Find Out More > </p>
                                                    </div>
                                                </div>
                                            </div>
                                        </div>
                                    </a></div>


                            </div>
                        </div>
                    </div>

                </div>
            </div>


            <div class="carousel-item" style="background-image: url('../Images/Filler.jpg')">
                <div class="carousel-caption">


                    <h3 class="font-weight-normal display-3">EDU Africa</h3>
                    <p class="BodyText">Educating Entrepreneurs, Innovators and Future international leaders</p>
                    <p class="LowerBodyText">Connecting students all around the world for a better AFRICA</p>

                    <div class="Buttons">
                        <div class="container">
                            <div class="row">
                                <div class="col-sm-4 right-button">
                                    <a href="">
                                        <div class="Textbox-outside">
                                            <div class="row">
                                                <div class="col-sm-12">
                                                    <div class="Text-inside">
                                                        <h4>E For Environment </h4>
                                                        <p>Find Out More > </p>
                                                    </div>
                                                </div>
                                            </div>
                                        </div>
                                    </a></div>


                                <div class="col-sm-4 center-button">
                                    <a href="">
                                        <div class="Textbox-outside">
                                            <div class="row">
                                                <div class="col-sm-12">
                                                    <div class="Text-inside">
                                                        <h4>C For Community </h4>
                                                        <p>Find Out More > </p>
                                                    </div>
                                                </div>
                                            </div>
                                        </div>
                                    </a></div>


                                <div class="col-sm-4 left-button">
                                    <a href="">
                                        <div class="Textbox-outside">
                                            <div class="row">
                                                <div class="col-sm-12">
                                                    <div class="Text-inside">
                                                        <h4>O For Organisation</h4>
                                                        <p>Find Out More > </p>
                                                    </div>
                                                </div>
                                            </div>
                                        </div>
                                    </a></div>


                            </div>
                        </div>
                    </div>

                </div>
            </div>


        </div>


    </div>
    <a class="carousel-control-prev" href="#carouselExampleIndicators" role="button" data-slide="prev">
        <span class="carousel-control-prev-icon" aria-hidden="true"></span>
        <span class="sr-only">Previous</span>
    </a>
    <a class="carousel-control-next" href="#carouselExampleIndicators" role="button" data-slide="next">
        <span class="carousel-control-next-icon" aria-hidden="true"></span>
        <span class="sr-only">Next</span>
    </a>


    <!--Requires a footer, instead of typing it out, possibly causing errors-->

<?php require('templates/footer.phtml') ?>