<footer>

    <nav class="navbar navbar-default">
        <div class="container">
            <div class="row">
                <div class="Logo">
                    <a href="index.html"><img src="images/IFA-Logo.png" alt="IFA Logo" style="width: 32%;"></a>
                </div>
            </div>


            <ul id="menu-main-menu" class="nav navbar-nav navbar-right">
                <div class="Bot-Nav-Bar">
                    <li><a href="" style=""> Events</a></li>
                    <li><a href="" style=""> FAQs</a></li>
                    <li><a href="" style=""> Sitemap</a></li>
                </div>
            </ul>
        </div>


    </nav>

    <hr>
    <div class="container">
        <div class="btsp">
            <div class="row">
                <div class="col-sm-4">

                    <h4>© Copyright Lorum Ipsum</h4>
                </div>
                <div class="col-sm-8">
                    <h5>IFA Lorum Ipsum Lorum Ipsum Lorum Ipsum Lorum Ipsum Lorum Ipsum Lorum Ipsum</h5>
                </div>
            </div>
        </div>
    </div>
</footer>

<!--close content wrapper-->
</div>

</body>


<script src="https://code.jquery.com/jquery-3.2.1.slim.min.js"
        integrity="sha384-KJ3o2DKtIkvYIK3UENzmM7KCkRr/rE9/Qpg6aAZGJwFDMVNA/GpGFF93hXpG5KkN"
        crossorigin="anonymous"></script>
<script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.12.3/umd/popper.min.js"
        integrity="sha384-vFJXuSJphROIrBnz7yo7oB41mKfc8JzQZiCq4NCceLEaO4IHwicKwpJf9c9IpFgh"
        crossorigin="anonymous"></script>
<script src="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0-beta.2/js/bootstrap.min.js"
        integrity="sha384-alpBpkh1PFOepccYVYDB4do5UnbKysX5WZXm3XxPqe5iKTfUKjNkCk9SaVuEZflJ"
        crossorigin="anonymous"></script>

</html>
