<!DOCTYPE HTML>
<html>
<head>
    <meta charset="utf-8"/>

    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0-beta.2/css/bootstrap.min.css"
          integrity="sha384-PsH8R72JQ3SOdhVi3uxftmaW6Vc51MKb0q5P2rRUpPvrszuE4W1povHYgTpBfshb" crossorigin="anonymous">
    <link href="https://maxcdn.bootstrapcdn.com/font-awesome/4.7.0/css/font-awesome.min.css" rel="stylesheet"
          integrity="sha384-wvfXpqpZZVQGK6TAh5PVlGOfQNHSoD2xbE+QkPxCAFlNEevoEH3Sl0sibVcOQVnN" crossorigin="anonymous">
    <link rel="stylesheet" href="../../Css/Styles.css">
    <title>ECO</title>
</head>

<body>

<header id="header" role="banner">
    <div id="topbar">
        <div class="container">
            <div class="row">
                <div class="col-sm-10">
                    <ul class="list-inline" id="social-icons">
                        <li>
                            <a href="" target="_blank"><i class="fa fa-facebook"></i></a>
                        </li>
                        <li>
                            <a href="" target="_blank"><i class="fa fa-instagram"></i></a>
                        </li>

                        <li>
                            <a href="" target="_blank"><i class="fa fa-twitter-square"></i></a>
                        </li>
                    </ul>
                </div>
                <div class="col-sm-1">
                    <div class="joinlinks">
                        <a href=""><p>Join Us</p></a>
                    </div>
                </div>

                <div class="col-sm-1">
                    <div class="joinlinks">
                        <a href="../../login.php"><p>Log In</p></a>
                    </div>
                </div>
            </div>
        </div>
    </div>


    <div class="navbar navbar-default ">
        <div class="container">
            <div class="row">
                <div class="Logo">
                    <a class="navbar-brand" href="../../index.php"><img src="Images/IFA-Logo.png" alt="IFA Logo"
                                                                        style="width: 32%;"></a>
                </div>
            </div>


            <ul id="menu-main-menu" class="nav navbar-nav navbar-right">
                <ul class="nav navbar-nav navbar-right">
                    <div class="Nav-Bar">
                        <li><a href="../../about-us.php" style=""> About</a></li>
                        <li><a href="ECO-Africa.html" style=""> Eco-Africa</a></li>
                        <li><a href="" style=""> Innovation Meter</a></li>
                        <li class="dropdown">
                            <a href="#" class="dropdown-toggle" data-toggle="dropdown" role="button"
                               aria-haspopup="true" aria-expanded="false">Opportunities <span class="caret"></span></a>
                            <ul class="dropdown-menu">
                                <li><a href="#">Volunteering</a></li>
                                <li><a href="#">Internship</a></li>
                                <li><a href="#">Apprentiship</a></li>
                                <li><a href="#">Jobs</a></li>
                            </ul>
                        </li>
                        <li><a href="../../contact-us.php" style=""> Contact Us</a></li>
                    </div>
                </ul>
            </ul>
        </div>
    </div>

</header>

<!--start content wrapper-->
<div class="content-wrapper">



